// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxj_zalfemzt5uuqr5HZE7mRyjVgPth6Q',
    appId: '1:277182412918:web:986046d5d9cf40fad38757',
    messagingSenderId: '277182412918',
    projectId: 'sos-cidade-8adf3',
    authDomain: 'sos-cidade-8adf3.firebaseapp.com',
    storageBucket: 'sos-cidade-8adf3.firebasestorage.app',
    measurementId: 'G-5BHFYB5EWH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQfqzNEpGY4zOxTw4UT8yegK5-fUIiANY',
    appId: '1:277182412918:android:1ae515ee6d7701d6d38757',
    messagingSenderId: '277182412918',
    projectId: 'sos-cidade-8adf3',
    storageBucket: 'sos-cidade-8adf3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARdpbNwLnYjDQ6qJVmPi_2wHyXzVSEL4E',
    appId: '1:277182412918:ios:ced22055cde6bdf6d38757',
    messagingSenderId: '277182412918',
    projectId: 'sos-cidade-8adf3',
    storageBucket: 'sos-cidade-8adf3.firebasestorage.app',
    iosBundleId: 'com.example.sosCidade',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARdpbNwLnYjDQ6qJVmPi_2wHyXzVSEL4E',
    appId: '1:277182412918:ios:ced22055cde6bdf6d38757',
    messagingSenderId: '277182412918',
    projectId: 'sos-cidade-8adf3',
    storageBucket: 'sos-cidade-8adf3.firebasestorage.app',
    iosBundleId: 'com.example.sosCidade',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxj_zalfemzt5uuqr5HZE7mRyjVgPth6Q',
    appId: '1:277182412918:web:9895b07c09bc98dad38757',
    messagingSenderId: '277182412918',
    projectId: 'sos-cidade-8adf3',
    authDomain: 'sos-cidade-8adf3.firebaseapp.com',
    storageBucket: 'sos-cidade-8adf3.firebasestorage.app',
    measurementId: 'G-SXX6NTVQDJ',
  );
}
